# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT mysite.wsgi

beta_settings:
    cloud_sql_instances: iot-projects-185714:us-central1:django-db 

runtime_config:
  python_version: 3
# [END runtime]
